version: "3.4"

services:
  postgres:
    hostname: postgres
    image: postgres:15-alpine
    restart: always
    volumes:
      # This will create a docker volume to persist the database files in.
      # If you prefer those files to be outside of docker, you'll need to change this.
      - /home/triiq/docker/matrix/dendrite_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dickhead
      POSTGRES_USER: dendrite
      POSTGRES_DATABASE: dendrite
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dendrite"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
  monolith:
    hostname: monolith
    image: matrixdotorg/dendrite-monolith:latest
    ports:
      - 8008:8008
      - 8448:8448
    volumes:
      - /home/triiq/docker/matrix/config:/etc/dendrite
      # The following volumes use docker volumes, change this
      # if you prefer to have those files outside of docker.
      - /home/triiq/docker/matrix/dendrite_media:/var/dendrite/media
      - /home/triiq/docker/matrix/dendrite_jetstream:/var/dendrite/jetstream
      - /home/triiq/docker/matrix/dendrite_search_index:/var/dendrite/searchindex
      - /home/triiq/docker/matrix/:/mnt
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    attachable: true
volumes:
  dendrite_postgres_data:
  dendrite_media:
  dendrite_jetstream: