version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/triiq/docker/proxy/data:/data
      - /home/triiq/docker/proxy/letsencrypt:/etc/letsencrypt
