services:

  webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://10.9.9.101:11434
    volumes:
      - /home/triiq/docker/ollama/webui:/app/backend/data
    depends_on:
     - ollama
    network_mode: host
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    network_mode: host
    volumes:
      - /home/triiq/docker/ollama/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['all']
              capabilities: [gpu]
