version: '3.8'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL:http://127.0.0.1:11434
    ports:
      - "8282:8080"
    networks:
      - host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/triiq/docker/openwebui:/app/backend/data
    restart: unless-stopped