---
version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    ports:
      - 5056:5055
    volumes:
      - /home/triiq/docker/overseer/config:/app/config
    restart: unless-stopped