version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - 32400:32400
    volumes:
      - /home/triiq/docker/plex/config:/config
      - /mnt/media/watch/tv:/tv
      - /mnt/media/watch/movie:/movies
    restart: unless-stopped
   # runtime: nvidia