version: '3.7'
services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /home/triiq/docker/tubesync/config:/config
      - /home/triiq/docker/tubesync/downloads:/downloads
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000